export const DEFAULT_CATEGORIES = [
  {
    name: 'Problema de entrega',
    slug: 'delivery',
    description: 'No llegó, llegó tarde o a una dirección incorrecta',
    icon: 'Truck',
    color: '#2F6FED',
    default_priority: 1,
    sort_order: 0,
  },
  {
    name: 'Producto defectuoso',
    slug: 'defective',
    description: 'Defectuoso, incompleto o producto equivocado',
    icon: 'PackageX',
    color: '#DC2626',
    default_priority: 1,
    sort_order: 1,
  },
  {
    name: 'Cobro incorrecto',
    slug: 'billing',
    description: 'Cobro duplicado, monto incorrecto o cargo no reconocido',
    icon: 'CreditCard',
    color: '#D97706',
    default_priority: 1,
    sort_order: 2,
  },
  {
    name: 'Solicitud de devolución',
    slug: 'return',
    description: 'Arrepentimiento, cambio o no cumple expectativas',
    icon: 'RotateCcw',
    color: '#7C3AED',
    default_priority: 2,
    sort_order: 3,
  },
  {
    name: 'Garantía',
    slug: 'warranty',
    description: 'Solicitud de garantía o reparación',
    icon: 'Shield',
    color: '#059669',
    default_priority: 2,
    sort_order: 4,
  },
  {
    name: 'Otro',
    slug: 'other',
    description: 'Cualquier otra consulta o reclamo',
    icon: 'HelpCircle',
    color: '#64748B',
    default_priority: 3,
    sort_order: 5,
  },
];
